# Apriory Algorithm

In [1]:
# import numpy as np
# import pandas as pd
# from apyori import apriori

In [2]:
# store_data = pd.read_csv('../datasets/store_data.csv', header=None)
# store_data.head()

In [3]:
# num_records = len(store_data)
# num_records

In [4]:
# records = []
# for i in range(0, num_records):
#     records.append([str(store_data.values[i,j]) for j in range(0, 20)])

In [5]:
# association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=1)
# association_results = list(association_rules)

In [6]:
# print(len(association_results))  # to check the Total Number of Rules mined
# print(association_results[0])    # to print the first item the association_rules list to see the first rule

In [7]:
# # to display the rule, the support, the confidence, and lift for each rule in a more clear way
# for item in association_results:  

#     # first index of the inner list
#     # Contains base item and add item
#     pair = item[0] 
#     items = [x for x in pair]
#     print("Rule: " + items[0] + " -> " + items[1])

#     #second index of the inner list
#     print("Support: " + str(item[1]))

#     #third index of the list located at 0th of the third index of the inner list

#     print("Confidence: " + str(item[2][0][2]))
#     print("Lift: " + str(item[2][0][3]))
#     print("=====================================")

# Testing

In [8]:
# import operator
# from time import time
# from collections import defaultdict

In [9]:
# tic = time()
# THRESHOLD = 300

# item_counts = defaultdict(int)
# pair_counts = defaultdict(int)
# triple_counts = defaultdict(int)
# fourfold_counts = defaultdict(int)
# fivefold_counts = defaultdict(int)
# sixfold_counts = defaultdict(int)

In [10]:
# # read in the data
# with open('../datasets/file_1M.txt') as f:
#     lines = f.readlines()
# f.close() 

In [11]:
# def normalize_group(*args):
#     return str(sorted(args))

# def generate_pairs(*args):
#     pairs = []
#     for idx_1 in range(len(args) - 1):
#         for idx_2 in range(idx_1 + 1, len(args)):
#             pairs.append(normalize_group(args[idx_1], args[idx_2]))
#     return pairs

# def generate_triples(*args):
#     triples = []
#     for idx_1 in range(len(args) - 2):
#         for idx_2 in range(idx_1 + 1, len(args) - 1):
#             for idx_3 in range(idx_2 + 1, len(args)):
#                 triples.append(normalize_group(args[idx_1], args[idx_2], args[idx_3]))
#     return triples

# def generate_fourfolds(*args):
#     fourfolds = []
#     for idx_1 in range(len(args) - 3):
#         for idx_2 in range(idx_1 + 1, len(args) - 2):
#             for idx_3 in range(idx_2 + 1, len(args) - 1):
#                 for idx_4 in range(idx_3 + 1, len(args)):
#                     fourfolds.append(normalize_group(args[idx_1], args[idx_2], args[idx_3], args[idx_4]))
#     return fourfolds

# def generate_fivefolds(*args):
#     fivefolds = []
#     for idx_1 in range(len(args) - 4):
#         for idx_2 in range(idx_1 + 1, len(args) - 3):
#             for idx_3 in range(idx_2 + 1, len(args) - 2):
#                 for idx_4 in range(idx_3 + 1, len(args) - 1):
#                     for idx_5 in range(idx_4 + 1, len(args)):
#                         fivefolds.append(normalize_group(args[idx_1], args[idx_2], args[idx_3], args[idx_4], args[idx_5]))
#     return fivefolds

In [12]:
# # FIRST PASS -----------------------------------------

# # first pass - find candidate items
# for line in lines:
#     for item in line.split(', '):
#         item_counts[item] += 1

# # first pass - find frequent items
# frequent_items = set()
# for key in item_counts:
#     if item_counts[key] > THRESHOLD:
#         frequent_items.add(key)

# print('There are {0} unique items, {1} of which are frequent'.format(len(item_counts), len(frequent_items)))

There are 18069 unique items, 598 of which are frequent


In [13]:
# # SECOND PASS -----------------------------------------

# # second pass - find candidate pairs
# # when building candidate pairs, only consider frequent items
# for line in lines:
#     items = line.split(', ')
#     for idx_1 in range(len(items) - 1):
#         if items[idx_1] not in frequent_items:
#             continue
#         for idx_2 in range(idx_1 + 1, len(items)):
#             if items[idx_2] not in frequent_items:
#                 continue
#             pair = normalize_group(items[idx_1], items[idx_2]) # [a, b] is the same as [b, a]
#             pair_counts[pair] += 1

# # second pass - find frequent pairs
# frequent_pairs = set()
# for key in pair_counts:
#     if pair_counts[key] > THRESHOLD:
#         frequent_pairs.add(key)

# print('There are {0} candidate pairs, {1} of which are frequent'.format(len(pair_counts), len(frequent_pairs)))

There are 178208 candidate pairs, 659 of which are frequent


In [14]:
# # THIRD PASS -----------------------------------------

# # third pass - find candidate triples
# # when building candidate triples, only consider frequent items and pairs
# for line in lines:
#     items = line.split(', ')
#     for idx_1 in range(len(items) - 2):
#         if items[idx_1] not in frequent_items: # first item must be frequent
#             continue
#         for idx_2 in range(idx_1 + 1, len(items) - 1):
#             first_pair = normalize_group(items[idx_1], items[idx_2])
#             if items[idx_2] not in frequent_items or first_pair not in frequent_pairs: # second item AND first pair must be frequent
#                 continue
#             for idx_3 in range(idx_2 + 1, len(items)):
#                 if items[idx_3] not in frequent_items:
#                     continue
#                 # now check that all pairs are frequent, since this is a precondition to being a frequent triple
#                 pairs = generate_pairs(items[idx_1], items[idx_2], items[idx_3])
#                 if any(pair not in frequent_pairs for pair in pairs):
#                     continue
#                 triple = normalize_group(items[idx_1], items[idx_2], items[idx_3])
#                 triple_counts[triple] += 1

# # third pass - find frequent triples
# frequent_triples = set()
# for key in triple_counts:
#     if triple_counts[key] > THRESHOLD:
#         frequent_triples.add(key)

# print('There are {0} candidate triples, {1} of which are frequent'.format(len(triple_counts), len(frequent_triples)))

There are 2823 candidate triples, 151 of which are frequent


In [15]:
# # FOURTH PASS -----------------------------------------

# # fourth pass - find candidate fourfold
# # when building candidate fourfold, only consider frequent items, pairs, and triples
# for line in lines:
#     items = line.split(', ')
#     for idx_1 in range(len(items) - 3):
#         if items[idx_1] not in frequent_items: # first item must be frequent
#             continue
#         for idx_2 in range(idx_1 + 1, len(items) - 2):
#             first_pair = normalize_group(items[idx_1], items[idx_2])
#             if items[idx_2] not in frequent_items or first_pair not in frequent_pairs: # second item AND first pair must be frequent
#                 continue
#             for idx_3 in range(idx_2 + 1, len(items) - 1):
#                 second_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3])
#                 if items[idx_3] not in frequent_items or second_pair not in frequent_triples:
#                     continue   
#                 for idx_4 in range(idx_3 + 1, len(items)):
#                     if items[idx_4] not in frequent_items:
#                         continue
#                     # now check that all triples are frequent, since this is a precondition to being a frequent fourfold
#                     triples = generate_triples(items[idx_1], items[idx_2], items[idx_3], items[idx_4])
#                     if any(trip not in frequent_triples for trip in triples):
#                         continue
#                     fourfold = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4])
#                     fourfold_counts[fourfold] += 1

# # fourth pass - find frequent fourfold
# frequent_fourfold = set()
# for key in fourfold_counts:
#     if fourfold_counts[key] > THRESHOLD:
#         frequent_fourfold.add(key)

# print('There are {0} candidate fourfold, {1} of which are frequent'.format(len(fourfold_counts), len(frequent_fourfold)))                    

There are 35 candidate fourfold, 6 of which are frequent


In [16]:
# # FIFTH PASS -----------------------------------------

# # fifth pass - find candidate fivefold
# # when building candidate fivefold, only consider frequent items, pairs, triples, and fourfold
# for line in lines:
#     items = line.split(', ')
#     for idx_1 in range(len(items) - 4):
#         if items[idx_1] not in frequent_items:
#             continue
#         for idx_2 in range(idx_1 + 1, len(items) - 3):
#             first_pair = normalize_group(items[idx_1], items[idx_2])
#             if items[idx_2] not in frequent_items or first_pair not in frequent_pairs:
#                 continue
#             for idx_3 in range(idx_2 + 1, len(items) - 2):
#                 second_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3])
#                 if items[idx_3] not in frequent_items or second_pair not in frequent_triples:
#                     continue
#                 for idx_4 in range(idx_3 + 1, len(items) - 1):
#                     third_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4])
#                     if items[idx_4] not in frequent_items or third_pair not in frequent_fourfold:
#                         continue
#                     for idx_5 in range(idx_4 + 1, len(items)):
#                         if items[idx_5] not in frequent_items:
#                             continue
#                         # now check that all fourfold are frequent, since this is a precondition to being a frequent fivefold
#                         fourfolds = generate_fourfolds(items[idx_1], items[idx_2], items[idx_3], items[idx_4], items[idx_5])
#                         if any(four not in frequent_fourfold for four in fourfolds):
#                             continue
#                         fivefold = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4], items[idx_5])
#                         fivefold_counts[fivefold] += 1

# # fifth pass - find frequent fivefold
# frequent_fivefold = set()
# for key in fivefold_counts:
#     if fivefold_counts[key] > THRESHOLD:
#         frequent_fivefold.add(key)

# print('There are {0} candidate fivefold, {1} of which are frequent'.format(len(fivefold_counts), len(frequent_fivefold))) 

There are 0 candidate fourfold, 0 of which are frequent


In [17]:
# # SIXTH PASS -----------------------------------------

# # sixth pass - find candidate sixfold
# # when building candidate sixfold, only consider frequent items, pairs, triples, fourfold, and fivefold
# for line in lines:
#     items = line.split(', ')
#     for idx_1 in range(len(items) - 5):
#         if items[idx_1] not in frequent_items:
#             continue
#         for idx_2 in range(idx_1 + 1, len(items) - 4):
#             first_pair = normalize_group(items[idx_1], items[idx_2])
#             if items[idx_2] not in frequent_items or first_pair not in frequent_pairs:
#                 continue
#             for idx_3 in range(idx_2 + 1, len(items) - 3):
#                 second_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3])
#                 if items[idx_3] not in frequent_items or second_pair not in frequent_triples:
#                     continue
#                 for idx_4 in range(idx_3 + 1, len(items) - 2):
#                     third_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4])
#                     if items[idx_4] not in frequent_items or third_pair not in frequent_fourfold:
#                         continue
#                     for idx_5 in range(idx_4 + 1, len(items) - 1):
#                         fourth_pair = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4], items[idx_5])
#                         if items[idx_5] not in frequent_items or fourth_pair not in frequent_fivefold:
#                             continue
#                         for idx_6 in range(idx_5 + 1, len(items)):
#                             if items[idx_6] not in frequent_items:
#                                 continue
#                             # now check that all fourfold are frequent, since this is a precondition to being a frequent fivefold
#                             fivefolds = generate_fivefolds(items[idx_1], items[idx_2], items[idx_3], items[idx_4], items[idx_5], items[idx_6])
#                             if any(five not in frequent_fivefold for five in fivefolds):
#                                 continue
#                             sixfold = normalize_group(items[idx_1], items[idx_2], items[idx_3], items[idx_4], items[idx_5], items[idx_6])
#                             sixfold_counts[sixfold] += 1

# num_candidate_sixfold = len(sixfold_counts) # before filtering
# frequent_sixfold = { k: v for k, v in sixfold_counts.items() if v > THRESHOLD } # filter for frequent triples
# print('There are {0} candidate sixfold, {1} of which are frequent'.format(num_candidate_sixfold, len(frequent_sixfold)))

# # VIEW OUR RESULTS -------------------------------------
# print('--------------')
# sorted_frequent_sixfold = sorted(frequent_sixfold.items(), key=operator.itemgetter(1))

# for entry in sorted_frequent_sixfold:
#     print('{0}: {1}'.format(entry[0], entry[1]))

There are 0 candidate fivefold, 0 of which are frequent
--------------


In [18]:
# print('Preprocessing time: {} mins!'.format(int((time() - tic) / 60.0)))

Preprocessing time: 10 mins!


In [19]:
# print('There are {0} unique items, {1} of which are frequent'.format(len(item_counts), len(frequent_items)))
# print('There are {0} candidate pairs, {1} of which are frequent'.format(len(pair_counts), len(frequent_pairs)))
# print('There are {0} candidate triples, {1} of which are frequent'.format(len(triple_counts), len(frequent_triples)))
# print('There are {0} candidate fourfold, {1} of which are frequent'.format(len(fourfold_counts), len(frequent_fourfold)))
# print('There are {0} candidate fivefold, {1} of which are frequent'.format(len(fivefold_counts), len(frequent_fivefold)))
# print('There are {0} candidate sixfold, {1} of which are frequent'.format(num_candidate_sixfold, len(frequent_sixfold)))

There are 18069 unique items, 598 of which are frequent
There are 178208 candidate pairs, 659 of which are frequent
There are 2823 candidate triples, 151 of which are frequent
There are 35 candidate fourfold, 6 of which are frequent
There are 0 candidate fivefold, 0 of which are frequent
There are 0 candidate sixfold, 0 of which are frequent


In [20]:
# MovieLens 100K

# 1th PASS: There are 7249 unique items, 923 of which are frequent
# 2th PASS: There are 411802 candidate pairs, 3410 of which are frequent
# 3th PASS: There are 28879 candidate triples, 771 of which are frequent
# 4th PASS: There are 465 candidate fourfold, 118 of which are frequent
# 5th PASS: There are 9 candidate fivefold, 7 of which are frequent
# 6th PASS: There are 0 candidate sixfold, 0 of which are frequent

# MovieLens 1M 300
# There are 18069 unique items, 598 of which are frequent
# There are 178208 candidate pairs, 659 of which are frequent
# There are 2823 candidate triples, 151 of which are frequent
# There are 35 candidate fourfold, 6 of which are frequent
# There are 0 candidate fivefold, 0 of which are frequent
# There are 0 candidate sixfold, 0 of which are frequent

# MovieLens 1M 430
# There are 18069 unique items, 280 of which are frequent
# There are 38955 candidate pairs, 167 of which are frequent
# There are 399 candidate triples, 11 of which are frequent
# There are 1 candidate fourfold, 0 of which are frequent
# There are 0 candidate fivefold, 0 of which are frequent
# There are 0 candidate sixfold, 0 of which are frequent

# MovieLens 1M 500
# There are 18069 unique items, 198 of which are frequent
# There are 19435 candidate pairs, 87 of which are frequent
# There are 163 candidate triples, 3 of which are frequent
# There are 0 candidate fourfold, 0 of which are frequent
# There are 0 candidate fivefold, 0 of which are frequent
# There are 0 candidate sixfold, 0 of which are frequent

### Build:  frequent_counts

Triples

In [21]:
# num_candidate_triples = len(triple_counts) # before filtering
# frequent_triple_counts = { k: v for k, v in triple_counts.items() if v > THRESHOLD } # filter for frequent triples
# print('There are {0} candidate triples, {1} of which are frequent'.format(num_candidate_triples, len(frequent_triple_counts)))

# # VIEW OUR RESULTS -------------------------------------
# print('--------------')
# sorted_triples = sorted(frequent_triple_counts.items(), key=operator.itemgetter(1))

# for entry in sorted_triples:
#     print('{0}: {1}'.format(entry[0], entry[1]))

Fourfold

In [22]:
# num_candidate_fourfold = len(fourfold_counts) # before filtering
# frequent_fourfold = { k: v for k, v in fourfold_counts.items() if v > THRESHOLD } # filter for frequent triples
# print('There are {0} candidate fourfold, {1} of which are frequent'.format(num_candidate_fourfold, len(frequent_fourfold)))

# # VIEW OUR RESULTS -------------------------------------
# print('--------------')
# sorted_frequent_fourfold = sorted(frequent_fourfold.items(), key=operator.itemgetter(1))

# for entry in sorted_frequent_fourfold:
#     print('{0}: {1}'.format(entry[0], entry[1]))

Fivefold

In [23]:
# num_candidate_fivefold = len(fivefold_counts) # before filtering
# frequent_fivefold = { k: v for k, v in fivefold_counts.items() if v > THRESHOLD } # filter for frequent triples
# print('There are {0} candidate fivefold, {1} of which are frequent'.format(num_candidate_fivefold, len(frequent_fivefold)))

# # VIEW OUR RESULTS -------------------------------------
# print('--------------')
# sorted_frequent_fivefold = sorted(frequent_fivefold.items(), key=operator.itemgetter(1))

# for entry in sorted_frequent_fivefold:
#     print('{0}: {1}'.format(entry[0], entry[1]))

Sixfold

In [24]:
# num_candidate_sixfold = len(sixfold_counts) # before filtering
# frequent_sixfold = { k: v for k, v in sixfold_counts.items() if v > THRESHOLD } # filter for frequent triples
# print('There are {0} candidate sixfold, {1} of which are frequent'.format(num_candidate_sixfold, len(frequent_sixfold)))

# # VIEW OUR RESULTS -------------------------------------
# print('--------------')
# sorted_frequent_sixfold = sorted(frequent_sixfold.items(), key=operator.itemgetter(1))

# for entry in sorted_frequent_sixfold:
#     print('{0}: {1}'.format(entry[0], entry[1]))

## Regularities Detection

In [12]:
# l_sized_regularities = []
# large_regularities = []
# final_set = []

In [13]:
# def separator(regularities):
#     seperated = []
#     for reg in regularities:
#         sep = re.split('Item_|: ', reg)   # seperate by ('Item_', ': ')
#         seperated.append(sep[1:])
        
#     return seperated

In [14]:
# def satisfying(reg_new):
#     ID_R = separator(reg_new)
#     size = len(ID_R)
#     count = 0
    
#     if size == 2:
#         for u_id in users:
#             temp = data_csv[((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[0][0]) & (data_csv['rating'] == ID_R[0][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[1][0]) & (data_csv['rating'] == ID_R[1][1]))].shape[0]
#             if temp == 2: count += 1
                
#     elif size == 3:
#         for u_id in users:
#             temp = data_csv[((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[0][0]) & (data_csv['rating'] == ID_R[0][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[1][0]) & (data_csv['rating'] == ID_R[1][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[2][0]) & (data_csv['rating'] == ID_R[2][1]))].shape[0]
#             if temp == 3: count += 1
                
#     elif size == 4:
#         for u_id in users:
#             temp = data_csv[((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[0][0]) & (data_csv['rating'] == ID_R[0][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[1][0]) & (data_csv['rating'] == ID_R[1][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[2][0]) & (data_csv['rating'] == ID_R[2][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[3][0]) & (data_csv['rating'] == ID_R[3][1]))].shape[0]
#             if temp == 4: count += 1
                
#     elif size == 5:
#         for u_id in users:
#             temp = data_csv[((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[0][0]) & (data_csv['rating'] == ID_R[0][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[1][0]) & (data_csv['rating'] == ID_R[1][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[2][0]) & (data_csv['rating'] == ID_R[2][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[3][0]) & (data_csv['rating'] == ID_R[3][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[4][0]) & (data_csv['rating'] == ID_R[4][1]))].shape[0]
#             if temp == 5: count += 1
                
#     elif size == 6:
#         for u_id in users:
#             temp = data_csv[((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[0][0]) & (data_csv['rating'] == ID_R[0][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[1][0]) & (data_csv['rating'] == ID_R[1][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[2][0]) & (data_csv['rating'] == ID_R[2][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[3][0]) & (data_csv['rating'] == ID_R[3][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[4][0]) & (data_csv['rating'] == ID_R[4][1])) |
#                             ((data_csv['user'] == u_id) & (data_csv['item'] == ID_R[5][0]) & (data_csv['rating'] == ID_R[5][1]))].shape[0]
#             if temp == 5: count += 1
#     else:
#         print('Size:', size)
        
#     return count

### First Stage

In [15]:
# tic = time()

# for i_id in items:
#     for d in range(1, 6):
#         count = data_csv[(data_csv['item'] == i_id) & (data_csv['rating'] == d)].shape[0]
#         if count >= minSup:
#             reg = ['Item_{0}: {1}'.format(i_id, d)]
#             l_sized_regularities.append(reg)
#             large_regularities.append(reg)
            
# print('Preprocessing time: {} seconds!'.format(int(time() - tic)))

### Second Stage

In [16]:
# tic = time()

# while large_regularities != []:
#     final_set = large_regularities
#     new_regularity_set = []
    
#     for reg_a in large_regularities:
#         for reg_b in l_sized_regularities:
            
#             if reg_b[0] not in reg_a:
#                 reg_new = sorted(reg_a + reg_b)
                
#                 if reg_new not in new_regularity_set:
#                     count = satisfying(reg_new)        # colculate count of users which satisfying 'reg_new'
                    
#                     if count >= minSup:
#                         new_regularity_set.append(reg_new)
                    
#     large_regularities = new_regularity_set
            
# print('Preprocessing time: {} seconds!'.format(int(time() - tic)))

### matrix_VS_matrix V: 1.0

In [16]:
# # stack all columns
# new_data = np.hstack((new_users, new_items, new_ratings))
# new_data

In [17]:
# # UsersID and ratings the same, but ItemsID from new_data without empty spaces
# matrix_VS_matrix = (data[:,2] == new_data[:,2]).all()
# matrix_VS_matrix

### matrix_VS_matrix V: 2.0

In [18]:
# # stack 2 columns from data and new_ratings
# new_data2 = np.hstack((data[:,:2], new_ratings))
# new_data2

In [19]:
# # Completely the same
# matrix_VS_matrix = (data[:,:3] == new_data2).all()
# matrix_VS_matrix

In [20]:
# toc = time()
# print('Preprocessing time: {} seconds!'.format(int(time() - toc)))

### If we want Remove empty spaces in items and build fast Matrix

In [11]:
# # users(6040), items(3706) and user_pos(1000209), item_pos(1000209)
# usersO, user_pos = np.unique(data[:, 0], return_inverse=True) # 'users' (unique list) & 'user_pos' (like in data (sorted))
# itemsO, item_pos = np.unique(data[:, 1], return_inverse=True) # 'items' (unique list) & 'item_pos' (like in data (sorted))

# # Prepare UsersID-ItemsID matrix 
# pivot_table = np.zeros((len(usersO), len(itemsO)), dtype=data.dtype)

# # Fit ratings to matrix
# pivot_table[user_pos, item_pos] = data[:, 2]  # reads 'data' row by row and fit 'rating'

In [12]:
# pivot_table

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]])

In [13]:
# # Change shapes
# user_pos = user_pos.reshape(-1, 1) + 1
# item_pos = item_pos.reshape(-1, 1) + 1
# rating_pos = data[:, 2].reshape(-1, 1)

In [14]:
# # Build a new data
# data_v2 = np.hstack((user_pos, item_pos, rating_pos))
# data_v2

array([[   1, 1105,    5],
       [   1,  640,    3],
       [   1,  854,    3],
       ...,
       [6040,  549,    5],
       [6040, 1025,    4],
       [6040, 1026,    4]], dtype=int64)

### Update

In [15]:
# usersN, user_pos = np.unique(data_v2[:, 0], return_inverse=True)
# itemsN, item_pos = np.unique(data_v2[:, 1], return_inverse=True)

# A Regularity-Based Preprocessing Method for Collaborative RSs 

In [2]:
import numpy as np
import pandas as pd
from time import time

In [3]:
TRIGGER = 'K'

if TRIGGER == 'K':
    N = 60
    diff = 1.5
    minSup = 70
    data = np.loadtxt('../datasets/main/ml-100k.data', skiprows=0, delimiter='\t').astype('int32')

elif TRIGGER == 'M':
    N = 5
    diff = 2.0
    minSup = 430
    data = np.loadtxt('../datasets/main/ml-1M.dat', skiprows=0, delimiter='::').astype('int32')

In [4]:
data_csv = pd.DataFrame(data, columns = ['user', 'item', 'rating', 'timestamp'])
data_csv.sort_values(['user', 'item'], ascending=[True, True], inplace=True)
data_csv.reset_index(inplace=True)
data_csv.drop('index', axis=1, inplace=True)
data_csv

user  item  rating  timestamp
0           1     1       5  978824268
1           1    48       5  978824351
2           1   150       5  978301777
3           1   260       4  978300760
4           1   527       5  978824195
...       ...   ...     ...        ...
1000204  6040  3683       4  960971696
1000205  6040  3703       4  964828575
1000206  6040  3735       4  960971654
1000207  6040  3751       4  964828782
1000208  6040  3819       5  963272166

[1000209 rows x 4 columns]

In [55]:
users = np.unique(data[:, 0]).tolist() # list of unique users
items = np.unique(data[:, 1]).tolist() # list of unique items

In [56]:
n_u = len(users)     # number of users
n_m = len(items)     # number of movies
n_r = data.shape[0]  # number of ratings

print("USERS: {}\t ITEMS: {}\t RATINGS: {}".format(n_u, n_m, n_r))

USERS: 6040	 ITEMS: 3706	 RATINGS: 1000209


In [57]:
# Make dict for users and movies, where udict[u_id] = index(0..942), and mdict[m_id] = index(0..1681)
udict = {}
for i, u_id in enumerate(users):
    udict[u_id] = i
    
mdict = {}
for i, m_id in enumerate(items):
    mdict[m_id] = i

In [58]:
support_matrix_users = np.zeros((n_u, 16), dtype='int32')
support_matrix_items = np.zeros((n_m, 16), dtype='int32')
matrix = np.zeros((n_u, n_m), dtype='float')

print(support_matrix_users.shape, support_matrix_items.shape)

(6040, 16) (3706, 16)


In [59]:
for i in range(n_r):
    u_id = data[i, 0]
    m_id = data[i, 1]
    r = data[i, 2]
    
    matrix[udict[u_id], mdict[m_id]] = int(r)

In [60]:
matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.]])

# userItemSet

In [10]:
def userItemSet(regul):
    temp_dic = dict()       
    for reg in regul:
        temp = []
        arc1 = 0
        arc2 = 0
        arc3 = 0

        for i, r in enumerate(reg[1:6]):
            if r!=0:
                arc1 = i+1

        for i, r in enumerate(reg[6:11]):
            if r!=0:
                arc2 = i+1

        for i, r in enumerate(reg[11:16]):
            if r!=0:
                arc3 = i+1

        temp_dic[reg[0]] = {'=': arc1, '>=': arc2, '<=': arc3} 

    return temp_dic

# Regularity_Generation

In [11]:
def Regularity_Generation(minSup, users, items):
    for u_id in users:
        support_matrix_users[udict[u_id], 0] = u_id
        for d in range(1, 6):
            support_eq = data_csv[(data_csv['user'] == u_id) & (data_csv['rating'] == d)].shape[0]
            support_eq_bg = data_csv[(data_csv['user'] == u_id) & (data_csv['rating'] >= d)].shape[0]
            support_eq_sm = data_csv[(data_csv['user'] == u_id) & (data_csv['rating'] <= d)].shape[0]
            
            support_matrix_users[udict[u_id], d] = support_eq if (support_eq > minSup) else 0
            support_matrix_users[udict[u_id], d+5] = support_eq_bg if (support_eq_bg > minSup) else 0
            support_matrix_users[udict[u_id], d+10] = support_eq_sm if (support_eq_sm > minSup) else 0
            
    for i_id in items:
        support_matrix_items[mdict[i_id], 0] = i_id
        for d in range(1, 6):
            support_eq = data_csv[(data_csv['item'] == i_id) & (data_csv['rating'] == d)].shape[0]
            support_eq_bg = data_csv[(data_csv['item'] == i_id) & (data_csv['rating'] >= d)].shape[0]
            support_eq_sm = data_csv[(data_csv['item'] == i_id) & (data_csv['rating'] <= d)].shape[0]
            
            support_matrix_items[mdict[i_id], d] = support_eq if (support_eq > minSup) else 0
            support_matrix_items[mdict[i_id], d+5] = support_eq_bg if (support_eq_bg > minSup) else 0
            support_matrix_items[mdict[i_id], d+10] = support_eq_sm if (support_eq_sm > minSup) else 0
            
    for row in support_matrix_users:
        temp = [x if (x == max(row[1:6])) or (x == max(row[6:11])) or (x == max(row[11:16])) else 0 for x in row[1:]]
        for i in range(15):
            support_matrix_users[udict[row[0]], i+1] = temp[i]
        
    for row in support_matrix_items:
        temp = [x if (x == max(row[1:6])) or (x == max(row[6:11])) or (x == max(row[11:16])) else 0 for x in row[1:]]
        for i in range(15):
            support_matrix_items[mdict[row[0]], i+1] = temp[i]
            
    dictUser = userItemSet(support_matrix_users)
    dictItem = userItemSet(support_matrix_items)
                
    return dictUser, dictItem

# FindAnomalousRatingsPerUser

In [12]:
def FindAnomalousRatingsPerUser(N, minSup, users, items):
    regForUsers, regForItems = Regularity_Generation(minSup, users, items)
    
    errorMatrix = np.zeros((n_u, n_m), dtype='float32')
            
        
    for u_id, values in regForUsers.items():
        for i in items:
            r = matrix[udict[u_id], mdict[i]]
            if (r!=0) and (values['='] != 0) and (values['='] != r) and (values['=']+1 != r) and (values['=']-1 != r):
                errorMatrix[udict[u_id], mdict[i]] = values['='] - r
              
            
    for i_id, values in regForItems.items():
        for u in users:
            r = matrix[udict[u], mdict[i_id]]
            if (r!=0) and (values['='] != 0) and (values['='] != r) and (values['=']+1 != r) and (values['=']-1 != r):
                if errorMatrix[udict[u], mdict[i_id]] == 0:
                    errorMatrix[udict[u], mdict[i_id]] = values['='] - r
                else:
                    errorMatrix[udict[u], mdict[i_id]] = (errorMatrix[udict[u], mdict[i_id]] + values['='] - r)/2.0
                                 
                        
    anomalousItemsPerUserList = {}
    for u in users:
        temp = {}
        for i, t in enumerate(errorMatrix[udict[u]]):
            if t != 0:
                temp[i] = t
        
        
        # Reduce dictionary  
        if len(temp) >= N:
            s = 0
            temp_cropped = {}
            temp_sorted = {i: value for i, value in sorted(temp.items(), key=lambda item: item[1], reverse=True)}
            for i, value in temp_sorted.items():
                s += 1
                temp_cropped[i] = value
                if s >= N:
                    break
            anomalousItemsPerUserList[udict[u]] = temp_cropped
        else:
            anomalousItemsPerUserList[udict[u]] = temp
        
        
    return anomalousItemsPerUserList

# Correction

In [13]:
def Correction(diff, N, minSup, users, items):
    anomalousItemsPerUserList = FindAnomalousRatingsPerUser(N, minSup, users, items)
    
    for u in users:            
        for i, values in anomalousItemsPerUserList[udict[u]].items():
            if abs(values) > diff:
                matrix[udict[u], i] += values
                
    return anomalousItemsPerUserList, matrix

# Run

In [14]:
tic = time()

anomalousItemsPerUserList, matrix = Correction(diff, N, minSup, users, items)

print('Preprocessing time: {} seconds!'.format(int(time() - tic)))

Preprocessing time: 751 seconds!


In [45]:
new_data = []

for u in users:
    for i in items:
        r = matrix[udict[u], mdict[i]]
        if r != 0:
            new_data.append([u, i, r])
            
new_data = np.array(new_data).astype('int32')

In [ ]:
new_data

In [16]:
anomalousItemsPerUserList

{0: {1107: 2.0},
 1: {20: 3.0, 1018: 2.0, 1123: 3.0, 1788: 2.0, 3032: 2.0},
 2: {579: 2.0, 1173: 2.0, 1504: 2.0, 2785: 2.0, 2898: 2.0},
 3: {1106: 3.0, 3294: 3.0},
 4: {46: 2.0,
  144: 2.0,
  309: 2.0,
  346: 4.0,
  347: 2.0,
  699: 3.0,
  1050: 3.0,
  1485: 2.0,
  1574: 3.0,
  1848: 3.0,
  2078: 2.0,
  2557: 2.0,
  2708: 3.0,
  2959: 2.0,
  3341: 3.0,
  3550: 2.0},
 5: {287: 3.0, 2651: 4.0},
 6: {3341: 2.0},
 7: {2131: 2.0, 2494: -2.0},
 8: {859: 2.0, 1142: 2.0, 2400: 2.0},
 9: {216: 2.0,
  802: 2.0,
  851: 2.0,
  852: 2.0,
  862: 2.0,
  863: 2.0,
  908: 2.0,
  1131: 2.0,
  1155: 2.0,
  1158: 2.0,
  1160: 2.0,
  1212: 2.0,
  1288: 2.0,
  1295: 2.0,
  1485: 2.0,
  1832: -2.0,
  1919: -2.0,
  2651: 2.0,
  2748: 2.0},
 10: {46: 2.0,
  106: 2.0,
  347: 3.0,
  426: 2.0,
  1186: 2.0,
  1445: 3.0,
  1545: 3.0,
  2162: 3.0,
  2203: 3.0,
  2501: 2.0},
 11: {1142: 2.0, 1155: 2.0, 1160: 2.0},
 12: {443: 2.0, 1142: 2.0},
 13: {593: 4.0, 1788: 2.0, 2651: 2.0, 2748: 3.0},
 14: {287: 2.0,
  347: 3.0

# Testing

In [55]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [56]:
# Sort ndArrray
data_csv = pd.DataFrame(data, columns = ['user', 'item', 'rating', 'timestamp'])
data_csv.sort_values(['user', 'item'], ascending=[True, True], inplace=True)
data_csv.reset_index(inplace=True)
data_csv.drop('index', axis=1, inplace=True)

data = np.array(data_csv)
data

array([[        1,         1,         5, 978824268],
       [        1,        48,         5, 978824351],
       [        1,       150,         5, 978301777],
       ...,
       [     6040,      3735,         4, 960971654],
       [     6040,      3751,         4, 964828782],
       [     6040,      3819,         5, 963272166]])

## Building a Matrix

In [57]:
# users(6040), items(3706) and user_pos(1000209), item_pos(1000209)
users, user_pos = np.unique(data[:, 0], return_inverse=True) # 'users' (unique list) & 'user_pos' (like in data (sorted))
items, item_pos = np.unique(data[:, 1], return_inverse=True) # 'items' (unique list) & 'item_pos' (like in data (sorted))

# Prepare UsersID-ItemsID matrix 
pivot_table = np.zeros((len(users), len(items)), dtype=data.dtype)

# Fit ratings to matrix
pivot_table[user_pos, item_pos] = data[:, 2]  # reads 'data' row by row and fit 'rating'

In [58]:
pivot_table.shape

(6040, 3706)

In [59]:
pivot_table

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]])

## Unpacking the Matrix

In [60]:
# Users column
new_users = user_pos.reshape(-1, 1) + 1
new_users

array([[   1],
       [   1],
       [   1],
       ...,
       [6040],
       [6040],
       [6040]], dtype=int64)

In [61]:
# Items column
new_items = item_pos.reshape(-1, 1) + 1
new_items

array([[   1],
       [  48],
       [ 145],
       ...,
       [3494],
       [3509],
       [3576]], dtype=int64)

In [62]:
# Ratings column
new_ratings = pivot_table.reshape(len(users) * len(items), 1)
new_ratings = new_ratings[new_ratings != 0].reshape(-1, 1)
new_ratings

array([[5],
       [5],
       [5],
       ...,
       [4],
       [4],
       [5]])

### matrix_VS_matrix V: 1.0

In [64]:
# stack all columns
new_data = np.hstack((new_users, new_items, new_ratings))
new_data

array([[   1,    1,    5],
       [   1,   48,    5],
       [   1,  145,    5],
       ...,
       [6040, 3494,    4],
       [6040, 3509,    4],
       [6040, 3576,    5]], dtype=int64)

In [74]:
# UsersID and ratings the same, but ItemsID from new_data without empty spaces
matrix_VS_matrix = (data[:,2] == new_data[:,2]).all()
matrix_VS_matrix

True

### matrix_VS_matrix V: 2.0

In [75]:
# stack 2 columns from data and new_ratings
new_data2 = np.hstack((data[:,:2], new_ratings))
new_data2

array([[   1,    1,    5],
       [   1,   48,    5],
       [   1,  150,    5],
       ...,
       [6040, 3735,    4],
       [6040, 3751,    4],
       [6040, 3819,    5]])

In [76]:
# Completely the same
matrix_VS_matrix = (data[:,:3] == new_data2).all()
matrix_VS_matrix

True

# End